name: grassh
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: 3.22.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  intl: any
  package_info_plus: ^8.0.0
  provider: ^6.1.2
  toml: ^0.16.0
  vector_graphics: ^1.1.11+1
  window_manager: ^0.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/gsh-logo.vec
    - assets/images/gsh-logo-light.vec
    - assets/images/icons/gsh-folder.vec
  fonts:
    - family: Twemoji
      fonts:
        - asset: assets/fonts/Twemoji.Mozilla.ttf
